info:
  name: manjaro_jupyterlab
  project: severstal
  layout: segment
  expdir: ../
executors:
  preprocess:
    type: preprocess
  masks:
    type: masks
    depends: preprocess
  train:
    type: catalyst
    gpu: 1
    args:
      config: configs/catalyst.yml
    depends: masks
    trace: trace.pth
    grid:
      - - encoder: inceptionresnetv2
          batch_size: 16
        - encoder: se_resnext50_32x4d
          batch_size: 16