info:
  name: manjaro_jupyterlab
  project: severstal
  layout: segment
  expdir: ../
executors:
  preprocess:
    type: preprocess
  masks:
    type: masks
    depends: preprocess
  train:
    type: catalyst
    gpu: 1
    args:
      config: configs/catalyst.yml
    depends: masks
    trace: trace.pth
    grid:
      - - encoder: se_resnext50_32x4d
          batch_size: 24
        - model_params:
            model: MobileUnet
            input_size: 256
            pretrained: True
            num_classes: 4
            layerwise_params: {}
        - encoder: resnet50
          batch_size: 22
        